---
- name: Converge
  hosts: all

  vars:
    # nginx_controller_user_email: "user@example.com"
    # nginx_controller_user_password: "mySecurePassword"
    # nginx_controller_fqdn: "controller.mydomain.com"
    # nginx_controller_validate_certs: false
    # nginx_controller_environment:
    #   metadata:
    #     name: "dev-sandbox"
    #     displayName: "developer sandbox environment"
    #     description: "sandbox environment for internal development"

    tasks:
    - include_role:
        name: ansible-role-nginx_controller_environment
